name: Metrics (languages recent)
on:
  push:
    branches:
      - init-readme
  schedule:
    - cron: "0 */12 * * *" # 2x per day
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ldjelouah
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics-languages.svg
          base: ""
          config_timezone: Europe/Paris

          # Include repos from your org as well
          repositories_affiliations: owner,collaborator,organization_member

          # --- Languages ---
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent: yes
          plugin_languages_recent_days: 90
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_threshold: 0
          # Optional: ignore some languages
          # plugin_languages_ignored: html, css
