name: Metrics (languages recent)
on:
  push:
    branches:
      - init-readme
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:


jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ldjelouah
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: metrics-languages.svg
          base: ""
          config_timezone: Europe/Paris

          # --- Langages, récemment utilisés ---
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent: yes
          plugin_languages_recent_days: 14   # fenêtre “récemment” (7/14/30…)
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          # Optionnel : ignorer certains langages
          # plugin_languages_ignored: html, css
