name: Metrics (languages recent)
on:
  push:
    branches:
      - init-readme
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Utilisateur GitHub
          user: ldjelouah

          # Token avec accès privé (scopes: repo, read:user)
          token: ${{ secrets.METRICS_TOKEN }}

          # Template
          template: classic
          filename: metrics-languages.svg

          # Pas de base content, seulement le plugin langages
          base: ""

          # Config générale
          config_timezone: Europe/Paris

          # --- Langages ---
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent: yes
          plugin_languages_recent_days: 90
          plugin_languages_limit: 20
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          plugin_languages_colors: github

          # Optionnel : inclure les forks si tu veux plus de stats
          # repositories_forks: yes
